server:
  port: 4050

spring:
  rabbitmq:
    host: 192.168.0.228
    port: 15672
    username: zhanglong
    password: 123456

sms:
  aliyun:
    accessKey: accessKey
    secretKey: secretKey
    channels:
      loginCodeChannel: SMS_34630023